spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "C:/Users/SAILS-DM583/Music/micro/config-server/src/main/resources/config"
server:
  port: 8071